# name: Publish to GH Pages

# on:
#   push:
#     branches:
#     - master

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2
#     - uses: actions/setup-node@v2
#       with:
#         node-version: '14'
#     - uses: actions/cache@v2
#       with:
#         path: ~/.npm
#         key: npm-${{hashFiles('**/package-lock.json')}}
#         restore-keys: npm-${{hashFiles('**/package-lock.json')}}
#     - name: NPM install
#       run: npm ci --omit=dev --omit=optional
#     - name: Build project
#       run: npm run build
#     - uses: LuisEnMarroquin/gh-pages-publish@v2.4.4
#       with:
#         FOLDER: build
#         SSHKEY: ${{ secrets.SSH }}
